baseURL = "https://arrihu.github.io/"
title = "Arrihu Archery"
theme = "mediumish-gohugo-theme"
themesDir = "./themes"
publishDir = "./docs"

copyright = "Arrihu Archery - All rights reserved"
paginate = 3
languageCode = "en"
defaultContentLanguage = "en"

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true

# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

disqusShortname = ""
googleAnalytics = ""

[outputs]
    home = ["HTML", "JSON", "RSS"]

# prevent build failures when using Hugo's template _internal/opengraph.html 
[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"

[markup]
    [markup.highlight]
        noClasses = true
        codeFences = true
        guessSyntax = true
        lineNos = true
        lineNumbersInTable = false
        style = "dracula"

    [markup.goldmark.renderer]
        unsafe = true


[params]
#   logo = "/images/logo.png"
  description ="the clean blog!"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
    name = "John Doe"
    thumbnail = "/images/author.png"
    description = "Creator of this blog."

[params.index]
    #   picture = "/images/author.png"
    title = "Arrihu Archery"
    subtitle = "The arrow is like a word, and the bow is your lips. Once you have released it, you cannot take it back."
    mdtext = '''Currently trying to get this blog running, still don't know what the blog will be about!\
    **This textblock is a demonstration of the mdtext-param.**\
    ### This is a markdown heading
    '''
    alertbar = false


[params.social]
    github = "<username>"
    linkedin = "<username>"
    xing = "<username>"
    medium = "<username>"
    twitter = "<username>"


[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = -100
    
    
    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/posts"
        weight = 10
            [[menu.main.blog]]
                identifier = "blog"
                name = "Blog"
                url = "/posts"
                weight = 15
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 50


# [params]
# author = "Arrihu"
# description = "Arrihu Archery personal website"
# keywords = "arrihu,archery,sport"
# img_home = "img/home-bg.jpg"
# img_404 = "img/404-bg.jpg"

useFaviconGenerator = true




custom_js = []
custom_css = [] # ["css/custom.css"]  Add your file to assets folder  [assets/css/custom.css]

[params.sidebar]
    enable = false
    gravatarEmail = ""
    # Overwritten by your gravatar image if `gravatarEmail` is filled
    avatar = "img/home-bg.jpg"
    bio = "a personal website"

# See https://giscus.app/
[params.giscus]
    enable = true
    repo = "roninro/hugo-theme-puppet"
    repo_id = "R_kgDOHuvyhw"
    category = "General"
    category_id = "DIC_kwDOHuvyh84CQjDo"
    input_position = "top"
    theme = "light_tritanopia"
    lang = "en"